"""
Error Handler Node — Graceful fallback when agent nodes fail.
Produces a safe, template-based report without LLM dependency.
"""

from agent.state import AgentState
from config import RISK_LABELS


# Pre-defined fallback recommendations per risk level
_FALLBACK_RECOMMENDATIONS = {
    "Low": [
        "Continue maintaining your current healthy lifestyle habits.",
        "Ensure regular physical activity — aim for at least 150 minutes per week.",
        "Monitor your sleep quality and maintain a consistent schedule (7–9 hours).",
        "Schedule periodic wellness check-ups to sustain good health.",
    ],
    "Moderate": [
        "Review your current workload and stress management strategies.",
        "Prioritise sleep — establish a consistent bedtime routine (7–9 hours).",
        "Increase physical activity if currently sedentary; aim for moderate intensity.",
        "Consider scheduling a consultation with a campus counsellor.",
        "Monitor your stress levels and practise mindfulness or relaxation techniques.",
    ],
    "High": [
        "Contact your campus wellness centre for a comprehensive assessment.",
        "Schedule an appointment with a healthcare provider as soon as possible.",
        "Review your academic workload with an academic adviser for possible adjustments.",
        "Implement immediate stress reduction strategies: breathing exercises, short walks.",
        "Reach out to your support network — friends, family, or peer mentors.",
    ],
}

_DISCLAIMER = (
    "This report is generated by an AI-powered health assessment tool and "
    "is intended for educational and informational purposes only. It is "
    "NOT a substitute for professional medical advice, diagnosis, or "
    "treatment. Always consult a qualified healthcare provider for "
    "medical concerns."
)


def error_handler_node(state: AgentState) -> dict:
    """
    Generate a safe fallback report when upstream nodes fail.

    This node does NOT require an LLM — it uses template-based
    recommendations to ensure the user always receives output.

    Reads: error, risk_score, risk_label, risk_class, top_features,
           patient_data
    Writes: health_report
    """
    risk_label = state.get("risk_label", "Moderate")
    risk_score = state.get("risk_score", 0.5)
    top_features = state.get("top_features", [])
    error_msg = state.get("error", "An unexpected error occurred.")

    # Build the fallback report
    recommendations = _FALLBACK_RECOMMENDATIONS.get(risk_label, _FALLBACK_RECOMMENDATIONS["Moderate"])
    recs_text = "\n".join(f"{i+1}. {r}" for i, r in enumerate(recommendations))
    features_text = ", ".join(top_features) if top_features else "Unable to determine"

    report = f"""## RISK SUMMARY

Patient has been classified as **{risk_label} Risk** with a probability \
score of {risk_score:.2f}. The primary contributing factors identified by \
the ML model are: {features_text}.

*Note: The AI reasoning module encountered an issue during analysis. This \
report uses pre-defined recommendations based on the risk classification.*

## PREVENTIVE RECOMMENDATIONS

{recs_text}

## CITED SOURCES

- WHO — Global Action Plan for NCD Prevention (general reference)
- CDC — Sleep and Sleep Disorders Guidelines (general reference)
- AHA — Cardiovascular Risk Reduction Guidelines (general reference)

*Sources are listed as general references. Detailed AI-grounded citations \
were unavailable due to a processing error.*

## MEDICAL DISCLAIMER

{_DISCLAIMER}

---
*System note: {error_msg}*
"""
    return {"health_report": report, "error": None}
